title:              Ziyi's Blog
email:              wang_ziyi@u.nus.edu
description:        Stay hungry, Stay foolish.
author:             Ziyi Wang
baseurl:  
url:                wangziyi2016.github.io

# Social Profiles
twitter_username:   
github_username:    wangziyi2016
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
